general:
  parameters:
    AvailabilityZones: $[taskcat_genaz_2]
    DomainAdminPassword: $[taskcat_genpass_16]
    QSS3BucketName: $[taskcat_autobucket]
project:
  name: quickstart-microsoft-fsx
  regions:
  - us-east-1
tests:
  default:
    template: ./templates/fsx-master-mad.yaml
