general:
  parameters:
    AvailabilityZones: $[taskcat_genaz_2]
    DomainAdminPassword: $[taskcat_genpass_16]
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    KeyPairName: $[taskcat_getkeypair]
    RDGWCIDR: 0.0.0.0/0
project:
  name: quickstart-fsx-windows-file-server
  regions:
  - us-east-1
  - us-east-2
  - eu-west-1
  - eu-west-2
  - ap-southeast-1
  - ap-northeast-1
tests:
  MAD:
    template: ./templates/fsx-windows-master.yaml
    parameters:
      ADScenarioType: AWS Managed Microsoft AD(Standard Edition)
      AvailabilityZones: $[taskcat_genaz_2]
      DeployRDGW: 'No'
      RDGWCIDR: 0.0.0.0/0
      KeyPairName: $[taskcat_getkeypair]
      DomainAdminPassword: $[taskcat_genpass_16]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    regions:
    - us-east-1
    - us-east-2
    - eu-west-1
    - eu-west-2
    - ap-southeast-1
    - ap-northeast-1
  SMAD:
    template: ./templates/fsx-windows-master.yaml
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      AvailabilityZones: $[taskcat_genaz_2]
      DeployRDGW: 'No'
      RDGWCIDR: 0.0.0.0/0
      KeyPairName: $[taskcat_getkeypair]
      DomainAdminPassword: $[taskcat_genpass_16]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    regions:
    - us-east-1
    - us-east-2
    - eu-west-1
    - eu-west-2
    - ap-southeast-1
    - ap-northeast-1
  GenKey:
    template: ./templates/fsx-windows-master.yaml
    parameters:
      ADScenarioType: AWS Managed Microsoft AD(Standard Edition)
      FSxEncryptionKey: GenerateKey
      AvailabilityZones: $[taskcat_genaz_2]
      DeployRDGW: 'No'
      RDGWCIDR: 0.0.0.0/0
      KeyPairName: $[taskcat_getkeypair]
      DomainAdminPassword: $[taskcat_genpass_16]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    regions:
    - us-east-1
    - us-east-2
    - ap-northeast-1
