AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates Amazon FSx for Windows File Server into private subnets in separate Availability Zones 
  inside a VPC and uses AWS Directory Service for Microsoft Active Directory or Self-Managed Active directory. **WARNING** 
  This template creates Amazon resources. You will be billed for the AWS resources used if you create a stack from this template. 
  (qs-1qdmcdqlc)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - PrivateSubnet1ID
          - PrivateSubnet2ID
          - VPCID
      - Label:
          default: FSx for Windows Configuration
        Parameters:
          - BackupRetention
          - DailyBackupTime
          - StorageCapacity
          - ThroughputCapacity
          - DomainMembersSG
          - FSxAllowedCIDR
          - FSxEncryptionKey
          - FSxExistingKeyID
          - WeeklyMaintenanceTime
      - Label:
          default: AWS Directory Service for Managed AD settings for FSx
        Parameters:
          - ActiveDirectoryId
      - Label:
          default: Self-Managed Active Directory settings for FSx
        Parameters:
          - DNSIP1
          - DNSIP2
          - DomainDNSName
          - FSxUserSecretsArn
          - OrgUnitDN
          - FileSystemAdminGroup
    ParameterLabels:
      ActiveDirectoryId:
        default: AWS Managed Microsoft AD Id
      BackupRetention:
        default: Automated backup retention
      DailyBackupTime:
        default: Daily backup start time
      DNSIP1:
        default: IP address of DNS Server
      DNSIP2:
        default: IP address of DNS Server
      DomainDNSName:
        default: FQDN of your self-managed directory 
      OrgUnitDN:
        default: Organizational Unit Distinguished Name
      FSxUserSecretsArn:
        default: AWS Secrets Manager secret Arn or name.
      FileSystemAdminGroup:
        default: Domain Group name
      FSxEncryptionKey:
        default: The type of KMS key used by FSx.
      FSxExistingKeyID:
        default: If Usekey is chosen must specify KMS Key Id
      DomainMembersSG:
        default: Domain Member Security Group ID
      PrivateSubnet1ID:
        default: Private Subnet 1 ID
      PrivateSubnet2ID:
        default: Private Subnet 2 ID
      StorageCapacity:
        default: Storage size in Gigabytes
      ThroughputCapacity:
        default: Throughput capacity of FSx file system
      FSxAllowedCIDR:
        default: CIDR ranged allowed to connect to FSx file system
      VPCID:
        default: VPC ID
      WeeklyMaintenanceTime:
        default: Weekly maintenance start time
Parameters:
  ActiveDirectoryId:
    Description: ID of the AWS Managed Microsoft AD, this can be left blank if not using AWS Managed Microsoft AD, but required if your are.
    Default: '' 
    Type: String
  BackupRetention:
    Description: The number of days to retain automatic backups. The default is to retain backups for 7 days. 
      Setting this value to 0 disables the creation of automatic backups. The maximum retention period 
      for backups is 35 days. 
    Default: 7
    Type: Number
  DailyBackupTime:
    Description: The preferred time to take daily automatic backups, formatted HH:MM in the UTC time zone 
    Default: '01:00'
    Type: String
  DNSIP1:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
    Description: First DNS IP address needed for self-managed Active Directory Scenario.This can be left blank 
      if not using self-managed AD, but required if your are. e.g. 10.0.0.1
    Default: '10.0.0.10' 
    Type: String
  DNSIP2:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
    Description: Second DNS IP address needed for self-managed Active Directory Scenario. This can be left blank 
      if not using self-managed AD, but required if your are. e.g. 10.0.0.1
    Default: '10.0.32.10' 
    Type: String
  DomainDNSName:
    AllowedPattern: '[a-zA-Z0-9\-]+\..+'
    Description: Fully qualified domain name (FQDN) of your self-managed directory. This can be left blank 
      if not using self-managed AD, but required if your are. Domain name must not be in the 
      Single Label Domain (SLD) format. e.g. example.com
    Default: example.com 
    Type: String
  FSxEncryptionKey:
    AllowedValues:
      - 'Default'
      - 'GenerateKey'
      - 'UseKey'
    Description: Use the default KMS key for FSx, Generate a Key or use an existing key for encryption at rest
      of the Amazon FSx for Windows file system 
    Default: 'Default'
    Type: String
  FSxExistingKeyID:
    Description: If you chose the option to use an existing key, you must specify the KMS Key ID you want to use. 
    Default: ''
    Type: String
  OrgUnitDN:
    Description: (Optional) The Organizational Unit (OU) Distinguished Name (DN) in your domain in which 
      you want your file system to be joined e.g. 'OU=FileSystems,DC=corp,DC=example,DC=com'
    Default: ''
    Type: String
  FSxUserSecretsArn:
    Description: Arn or secret name of secret in Secrets Manager for FSx to join your AD domain.
    Default: ''
    Type: String
  FileSystemAdminGroup:
    Description: (Optional) The domain group to which you want to delegate authority to 
      perform administrative actions on your file system. If you don’t specify this group, Amazon FSx delegates 
      this authority to the Domain Admins group in your AD domain by default.
    Default: '' 
    Type: String
  DomainMembersSG:
    Description: Security Group to be able to talk Domain Controllers
    Type: String
  PrivateSubnet1ID:
    Description: ID of the private subnet 1 in Availability Zone 1 (e.g., subnet-a0246dcd)
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2ID:
    Description: ID of the private subnet 2 in Availability Zone 2 (e.g., subnet-a0246dcd)
    Type: AWS::EC2::Subnet::Id
  StorageCapacity:
    Default: 32
    Description: The storage capacity of the file system being created, valid values are 32 GiB - 65,536 GiB.
      The default is set to the minimum value, but consider a high value for greater capacity. 
    Type: Number
  ThroughputCapacity:
    Default: 8
    Description: The throughput of an Amazon FSx file system, minimum value is 8 and maximum value is 2048. 
      The default is set to the minimum value, but consider a higher value for better performance.
    Type: Number
  FSxAllowedCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block that is allowed access to FSx
    Type: String
  VPCID:
    Description: ID of the VPC (e.g., vpc-0343606e)
    Type: AWS::EC2::VPC::Id
  WeeklyMaintenanceTime:
     Description: The preferred start time to perform weekly maintenance, formatted d:HH:MM in the UTC time zone
     Default: '7:02:00'
     Type: String
Conditions:
  UseAWSDirectoryService: !Not
    - !Equals
      - ''
      - !Ref 'ActiveDirectoryId'
  HasGroup: !Not
    - !Equals
      - ''
      - !Ref 'FileSystemAdminGroup'
  HasOU: !Not
    - !Equals
      - ''
      - !Ref 'OrgUnitDN'
  HasKey: !Equals
      - 'UseKey'
      - !Ref 'FSxEncryptionKey'
  CreateKey: !Equals
      - 'GenerateKey'
      - !Ref 'FSxEncryptionKey'
  UseNonDefault: !Not
    - !Equals
      - 'Default'
      - !Ref 'FSxEncryptionKey'
Resources:
  FSxKMSKey:
    Condition: CreateKey
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: !Ref AWS::StackName
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/fsx.amazonaws.com/AWSServiceRoleForAmazonFSx'
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
          - Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/fsx.amazonaws.com/AWSServiceRoleForAmazonFSx'
            Action:
              - 'kms:CreateGrant'
              - 'kms:ListGrants'
              - 'kms:RevokeGrant'
            Resource: '*'
            Condition:
              Bool:
                'kms:GrantIsForAWSResource': 'true'
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
  FSxKeyAlias:
    Condition: CreateKey
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}"
      TargetKeyId: !Ref FSxKMSKey
  FSxSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPCID
      GroupDescription: Security Group for FSx for Windows File Storage Access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 53
          ToPort: 53
          CidrIp: !Ref FSxAllowedCIDR
        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          CidrIp: !Ref FSxAllowedCIDR
        - IpProtocol: tcp
          FromPort: 88
          ToPort: 88
          CidrIp: !Ref FSxAllowedCIDR
        - IpProtocol: udp
          FromPort: 88
          ToPort: 88
          CidrIp: !Ref FSxAllowedCIDR
        - IpProtocol: udp
          FromPort: 123
          ToPort: 123
          CidrIp: !Ref FSxAllowedCIDR
        - IpProtocol: tcp
          FromPort: 135
          ToPort: 135
          CidrIp: !Ref FSxAllowedCIDR
        - IpProtocol: udp
          FromPort: 389
          ToPort: 389
          CidrIp: !Ref FSxAllowedCIDR
        - IpProtocol: tcp
          FromPort: 389
          ToPort: 389
          CidrIp: !Ref FSxAllowedCIDR
        - IpProtocol: udp
          FromPort: 445
          ToPort: 445
          CidrIp: !Ref FSxAllowedCIDR
        - IpProtocol: tcp
          FromPort: 445
          ToPort: 445
          CidrIp: !Ref FSxAllowedCIDR
        - IpProtocol: udp
          FromPort: 464
          ToPort: 464
          CidrIp: !Ref FSxAllowedCIDR
        - IpProtocol: tcp
          FromPort: 464
          ToPort: 464
          CidrIp: !Ref FSxAllowedCIDR
        - IpProtocol: tcp
          FromPort: 636
          ToPort: 636
          CidrIp: !Ref FSxAllowedCIDR
        - IpProtocol: tcp
          FromPort: 3268
          ToPort: 3268
          CidrIp: !Ref FSxAllowedCIDR
        - IpProtocol: tcp
          FromPort: 3269
          ToPort: 3269
          CidrIp: !Ref FSxAllowedCIDR
        - IpProtocol: tcp
          FromPort: 9389
          ToPort: 9389
          CidrIp: !Ref FSxAllowedCIDR
        - IpProtocol: tcp
          FromPort: 49152
          ToPort: 65535
          CidrIp: !Ref FSxAllowedCIDR
  WindowsFSx:
    Type: 'AWS::FSx::FileSystem'
    Properties:
      FileSystemType: WINDOWS
      KmsKeyId: !If
        - UseNonDefault
        - !If
          - HasKey
          - !Ref 'FSxExistingKeyID'
          - !Ref 'FSxKMSKey'
        - !Ref 'AWS::NoValue'
      StorageCapacity: !Ref 'StorageCapacity'
      SubnetIds:
        - !Ref 'PrivateSubnet1ID'
        - !Ref 'PrivateSubnet2ID'
      SecurityGroupIds:
        - !Ref 'DomainMembersSG'
        - !Ref 'FSxSecurityGroup'
      Tags:
        - Key: Name
          Value: QSWINFSx
      WindowsConfiguration: !If
        - UseAWSDirectoryService
        - ActiveDirectoryId: !Ref 'ActiveDirectoryId'
          WeeklyMaintenanceStartTime: !Ref 'WeeklyMaintenanceTime'
          DailyAutomaticBackupStartTime: !Ref 'DailyBackupTime'
          AutomaticBackupRetentionDays: !Ref 'BackupRetention'
          DeploymentType: MULTI_AZ_1
          PreferredSubnetId: !Ref 'PrivateSubnet1ID'
          ThroughputCapacity: !Ref 'ThroughputCapacity'
        - WeeklyMaintenanceStartTime: !Ref 'WeeklyMaintenanceTime'
          DailyAutomaticBackupStartTime: !Ref 'DailyBackupTime'
          AutomaticBackupRetentionDays: !Ref 'BackupRetention'
          DeploymentType: MULTI_AZ_1
          PreferredSubnetId: !Ref 'PrivateSubnet1ID'
          ThroughputCapacity: !Ref 'ThroughputCapacity'
          SelfManagedActiveDirectoryConfiguration:
            DnsIps: 
              - !Ref DNSIP1
              - !Ref DNSIP2
            DomainName: !Ref DomainDNSName
            FileSystemAdministratorsGroup: !If
              - HasGroup
              - !Ref 'FileSystemAdminGroup'
              - !Ref 'AWS::NoValue'
            OrganizationalUnitDistinguishedName: !If
              - HasOU
              - !Ref 'OrgUnitDN'
              - !Ref 'AWS::NoValue'
            UserName: !Join
              - ''
              - - '{{resolve:secretsmanager:'
                - !Ref FSxUserSecretsArn
                - ':SecretString:username}}'
            Password: !Join 
              - ''
              - - '{{resolve:secretsmanager:'
                - !Ref FSxUserSecretsArn
                - ':SecretString:password}}'
Outputs:
  FSxFileSystemID:
    Description: File System ID for FSx for Windows File Server
    Value: !Ref 'WindowsFSx'
  WindowsFSxSGID:
    Value: !Ref 'FSxSecurityGroup'
    Description: FSx for Windows File Server Security Group ID
